import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt



def get_predict():
	predict = pd.read_csv('../plot_entropy_rate_dt/refined_predictability_dist_only_POI_NSD_DBSCAN.csv', index_col=0)

	col = predict.columns
	usernames = []
	for c in col:
		usernames.append(c[:-4])

	predict.columns = usernames
	return predict

def get_questionare_answers():
	with open('/lscr_paper/amoellga/Data/Telefon/questiondic.p', 'rb') as f:
		answers = pickle.load(f)
	return answers

predict = get_predict()
usernames = predict.columns
answers = get_questionare_answers()
predict.loc[1] = np.nan


questions_list = answers[usernames[0]].keys()

for question_shorthand in questions_list:
	predict.loc[1] = np.nan
	for user in usernames:
		predict[user].loc[1] = answers[user][question_shorthand]['answer']

	if np.abs(predict.T.corr()[1][0]) > 0.15:
		print answers[user][question_shorthand]['question']
		print question_shorthand
		print 'Pearson correlation: ' + str(predict.T.corr()[1][0])
		predict.T.plot(kind='scatter', x=[0], y=[1])
		plt.show()
	elif np.abs(predict.T.corr()[1][0]) < 0.01:
		print 'NO CORR'
		print answers[user][question_shorthand]['question']
		print question_shorthand
		print 'Pearson correlation: ' + str(predict.T.corr()[1][0])
		
















# [u'function_duties',
#  u'narcissism_opponents',
#  u'locus_of_control_13',
#  u'locus_of_control_12',
#  u'self_efficacy_motto',
#  u'locus_of_control_10',
#  u'selfesteem_respect',
#  u'mdi_confidence',
#  u'bfi_worry',
#  u'worries_partner',
#  u'talk_father',
#  u'demands_zieblings',
#  u'function_alone',
#  u'alcohol_volume_sunday',
#  u'bfi_stable',
#  u'symptoms_back',
#  u'mdi_quiet',
#  u'bfi_few_art',
#  u'bfi_caring',
#  u'alcohol_binge5',
#  u'demands_partner',
#  u'loneliness_common',
#  u'sleep_wake',
#  u'alcohol_volume_thursday',
#  u'alcohol_volume_saturday',
#  u'symptoms_anxiety',
#  u'physical_function_physical',
#  u'conflicts_friends',
#  u'satisfaction_gain',
#  u'alcohol_very_drunk',
#  u'stress_overcome',
#  u'symptoms_shoulder',
#  u'bfi_helpfull',
#  u'selfesteem_doing_things',
#  u'narcissism_critisism',
#  u'conflicts_mother',
#  u'later_contact',
#  u'alcohol_volume_monday',
#  u'function_human',
#  u'alcohol_volume_tuesday',
#  u'locus_of_control_11',
#  u'help_friends',
#  u'selfesteem_failure',
#  u'symptoms_eczema',
#  u'panas_attention',
#  u'demands_mother',
#  u'loneliness_close',
#  u'mdi_restless',
#  u'panas_hostile',
#  u'electronic_contact_family',
#  u'sleep_time_wake',
#  u'narcissism_people',
#  u'mdi_guilty',
#  u'contact_friends',
#  u'involuntary_alone',
#  u'bfi_distract',
#  u'contact_partner',
#  u'ambition_mark',
#  u'demands_other_family',
#  u'stress_important',
#  u'help_father',
#  u'homophily_talent',
#  u'demands_father',
#  u'medicine_headache',
#  u'selfesteem_qualities',
#  u'stress_angry',
#  u'bfi_inventive',
#  u'bfi_tense',
#  u'function_freinds',
#  u'contact_mother',
#  u'electronic_contact_friends',
#  u'function_education',
#  u'bfi_talk',
#  u'talk_mother',
#  u'loneliness_alone',
#  u'physical_function_run',
#  u'weight',
#  u'bfi_reliable',
#  u'talk_zieblings',
#  u'sleep_time_falling',
#  u'drugs_30days',
#  u'contact_other_familily',
#  u'bfi_cold',
#  u'loneliness_wavelength',
#  u'smoke_daily',
#  u'bfi_rutine',
#  u'bfi_disorderly',
#  u'medicine_concentration',
#  u'mdi_depressed',
#  u'talk_partner',
#  u'loneliness_outgoing',
#  u'bf_complet',
#  u'locus_of_control_3',
#  u'demands_friends',
#  u'locus_of_control_1',
#  u'locus_of_control_7',
#  u'locus_of_control_6',
#  u'locus_of_control_5',
#  u'bfi_social',
#  u'self_efficacy_calm',
#  u'narcissism_sucess',
#  u'narcissism_famous',
#  u'homophily_importance',
#  u'smoke_freq',
#  u'bfi_fight',
#  u'homophily_popularity',
#  u'bfi_energi',
#  u'symptoms_stomachache',
#  u'homophily_popularity_dtu',
#  u'alcohol_volume_wednesday',
#  u'homophily_upbringing',
#  u'panas_present',
#  u'selfesteem_useless',
#  u'conflicts_father',
#  u'selfreported_health',
#  u'bfi_reserved',
#  u'panas_embarrased',
#  u'selfesteem_good',
#  u'bfi_imagination',
#  u'narcissism_gain',
#  u'narcissism_fantastic',
#  u'narcissism_looser',
#  u'alcohol_binge10',
#  u'self_efficacy_problems',
#  u'sleep_falling',
#  u'smoke_volume_cerut',
#  u'ambition_career',
#  u'worries_zieblings',
#  u'function_activity',
#  u'politic_do_well',
#  u'worries_other_family',
#  u'symptoms_indigestion',
#  u'bfi_quiet',
#  u'conflicts_partner',
#  u'bfi_creative',
#  u'alcohol_debut',
#  u'narcissism_attention',
#  u'conflicts_other_family',
#  u'bfi_confident',
#  u'trust_other',
#  u'loneliness_understand',
#  u'mdi_high_appetite',
#  u'stress_irritate',
#  u'panas_nervous',
#  u'help_other_family',
#  u'symptoms_palpitation',
#  u'panas_afraid',
#  u'bfi_effective',
#  u'narcissism_personality',
#  u'narcissism_centre',
#  u'stress_control',
#  u'bfi_strong_personality',
#  u'satisfaction_change',
#  u'medicine_physical',
#  u'loneliness_close_no',
#  u'mdi_concentration',
#  u'height',
#  u'stress_coping',
#  u'bfi_enthusiasm',
#  u'loneliness_miss',
#  u'selfesteem_valuable',
#  u'bfi_rude',
#  u'bfi_unbalanced',
#  u'talk_friends',
#  u'symptoms_tired',
#  u'worries_father',
#  u'help_zieblings',
#  u'mdi_sleep',
#  u'bfi_taste_art',
#  u'function_area',
#  u'symptoms_sleep',
#  u'homophily_talent_dtu',
#  u'narcissism_slick',
#  u'loneliness_meaningful',
#  u'narcissism_strength',
#  u'online_roleplay',
#  u'ambition_job',
#  u'selfesteem_positive',
#  u'self_efficacy_pass',
#  u'drugs_life',
#  u'drugs_other',
#  u'electronic_contact_partner',
#  u'physical_function_lift',
#  u'panas_goal',
#  u'locus_of_control_4',
#  u'panas_active',
#  u'mdi_life',
#  u'stress_upset',
#  u'medicine_pain',
#  u'homophily_socialize',
#  u'medicine_nervous',
#  u'satisfaction_ideal',
#  u'electronic_contact_mother',
#  u'loneliness_people_around',
#  u'birthyear',
#  u'know_other_number',
#  u'drugs_marihuana',
#  u'self_efficacy_goal',
#  u'loneliness_turn_to_no',
#  u'symptoms_leg',
#  u'bfi_original',
#  u'alcohol_drunk',
#  u'contact_father',
#  u'smoke_volume_pibe',
#  u'smoke_first_cigarette',
#  u'worries_freinds',
#  u'help_partner',
#  u'bfi_error',
#  u'alcohol_volume_friday',
#  u'live_alone',
#  u'contact_zieblings',
#  u'homophily_diligence',
#  u'symptoms_breath',
#  u'bfi_coorporation',
#  u'symptoms_cold',
#  u'religion',
#  u'bfi_hold_on',
#  u'mdi_low_appetite',
#  u'loneliness_turn_to',
#  u'help_mother',
#  u'bfi_currious',
#  u'loneliness_talk_to',
#  u'symptoms_depressed',
#  u'narcissism_special',
#  u'smoke_volume_cigar',
#  u'loneliness_isolated',
#  u'selfesteem_satisfied',
#  u'physical_function_exercise',
#  u'smoke_volume_cigarette',
#  u'loneliness_outside',
#  u'loneliness_ideas',
#  u'narcissism_worth',
#  u'panas_upset',
#  u'selfrated_appearance',
#  u'physical_function_run_8',
#  u'stress_difficulties',
#  u'bfi_work',
#  u'loneliness_shy',
#  u'homophily_diligence_dtu',
#  u'bfi_play',
#  u'medicine_depressed',
#  u'homophily_competent',
#  u'satisfaction_condition',
#  u'panas_inspired',
#  u'loneliness_know',
#  u'bfi_lazy',
#  u'lonelinessfriends_',
#  u'physical_activity',
#  u'talk_other_family',
#  u'drugs_12months',
#  u'electronic_contact_zieblings',
#  u'give_money',
#  u'narcissism_competitor',
#  u'bfi_shy',
#  u'bfi_depressed',
#  u'narcissism_irritation',
#  u'politic_poverty',
#  u'bfi_art',
#  u'locus_of_control_9',
#  u'stress_stress',
#  u'sleep_uncalm',
#  u'locus_of_control_8',
#  u'bfi_careless',
#  u'mdi_interest',
#  u'conflicts_zieblings',
#  u'alcohol_weekend',
#  u'bfi_relaxed',
#  u'homophily_sex',
#  u'sleep_early',
#  u'function_concentration',
#  u'worries_mother',
#  u'mdi_energy',
#  u'electronic_contact_other_family',
#  u'bfi_nervous',
#  u'stress_wish',
#  u'medicine_sleep',
#  u'symptoms_headache',
#  u'satisfaction_satisfied',
#  u'alcohol_everyday',
#  u'loneliness_together',
#  u'locus_of_control_2',
#  u'know_other',
#  u'bfi_forgive',
#  u'bfi_calm',
#  u'selfesteem_proud',
#  u'narcissism_excellent']
